modules = ["web"]
run = "run"

[nix]
channel = "stable-24_05"
packages = ["python3"]

[deployment]
run = ["python3", "-m", "http.server", "5000", "--bind", "0.0.0.0", "--directory", "."]

[workflows]
runButton = "Web Server"

[[workflows.workflow]]
name = "Web Server"
author = 41161414
mode = "sequential"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "python -m http.server 5000 --bind 0.0.0.0 --directory ."

# Add health check
[[workflows.workflow.tasks]]
task = "shell.exec"
args = "curl -f http://localhost:5000/ || exit 1"

# Add environment variables
[env]
PORT = "5000"
HOST = "0.0.0.0"

# Add build dependencies
[build]
dependencies = [
    "python3",
    "curl"
]

# Add deployment configuration
[deployment]
strategy = "rolling"
maxUnavailable = "0"
maxSurge = "1"

# Add monitoring
[monitoring]
enabled = true
path = "/health"
interval = "30s"
timeout = "5s" 